-- =============================================================
-- SQL Alert Definitions for Fraud Model Drift Monitoring
--
-- Source tables (auto-generated by Databricks Quality Monitor):
--   Profile: mlops.siva_borusu.customer_n_transactions_drift_profile_metrics
--   Drift:   mlops.siva_borusu.customer_n_transactions_drift_drift_metrics
--
-- Create each query block as a Databricks SQL Alert:
--   Schedule : daily at 08:30 AM America/Toronto (30 min after monitor refresh)
--   Trigger  : rows > 0
--   Notify   : siva.borusu@jrvs.ca
-- =============================================================


-- Alert 1: Feature drift vs baseline (KS / chi-squared)
-- Fires when ANY feature shows statistically significant drift
-- against the baseline (p-value < 0.05).
SELECT
  window.start   AS window_start,
  window.end     AS window_end,
  column_name,
  granularity,
  ks_test.statistic           AS ks_statistic,
  ks_test.pvalue              AS ks_pvalue,
  chi_squared_test.statistic  AS chi2_statistic,
  chi_squared_test.pvalue     AS chi2_pvalue,
  wasserstein_distance,
  population_stability_index  AS psi
FROM mlops.siva_borusu.customer_n_transactions_drift_drift_metrics
WHERE drift_type = 'BASELINE'
  AND slice_key IS NULL                          -- overall, not per-slice
  AND column_name NOT IN ('prediction', ':table') -- features only
  AND window.start >= current_date() - INTERVAL 1 DAY
  AND (
    ks_test.pvalue < 0.05
    OR chi_squared_test.pvalue < 0.05
  )
ORDER BY COALESCE(ks_test.pvalue, chi_squared_test.pvalue) ASC;


-- Alert 2: Model quality degradation
-- Fires when weighted precision, recall, or F1 drop below acceptable thresholds
-- in the latest monitoring window.
-- Note: precision/recall/f1_score are structs with .weighted, .macro, and
--       .one_vs_all fields.  accuracy is stored as accuracy_score (double).
SELECT
  window.start           AS window_start,
  window.end             AS window_end,
  granularity,
  model_version,
  accuracy_score,
  precision.weighted     AS precision_weighted,
  recall.weighted        AS recall_weighted,
  f1_score.weighted      AS f1_weighted
FROM mlops.siva_borusu.customer_n_transactions_drift_profile_metrics
WHERE column_name = ':table'
  AND log_type = 'INPUT'
  AND slice_key IS NULL
  AND window.start >= current_date() - INTERVAL 1 DAY
  AND (
    recall.weighted    < 0.40
    OR precision.weighted < 0.50
    OR f1_score.weighted  < 0.45
  );


-- Alert 3: Prediction distribution shift (PSI)
-- Fires when the prediction column's distribution has drifted
-- significantly from the baseline (PSI > 0.2).
SELECT
  window.start  AS window_start,
  window.end    AS window_end,
  granularity,
  population_stability_index AS psi,
  wasserstein_distance,
  avg_delta     AS prediction_mean_delta
FROM mlops.siva_borusu.customer_n_transactions_drift_drift_metrics
WHERE drift_type = 'BASELINE'
  AND column_name = 'prediction'
  AND slice_key IS NULL
  AND window.start >= current_date() - INTERVAL 1 DAY
  AND population_stability_index > 0.2;
